### ISSUE TITLE
Is it possible to update the code for saving tree structures and for tree plotting?

### ISSUE THREAD

**Issue by sky-Yongjie-Xu** [mvandenhi/sctree-public#1]
Is it possible to update the code for saving tree structures and for tree plotting?

**Comment by mvandenhi** [comment]
Hi Yongjie Xu,
Thank you for reaching out. We have added a Jupyter notebook to the main repository, which will visualize the learned tree. It requires some manual work depending on the dataset, however, the basic building blocks are the same. Please note that the trees are already automatically saved when running from the main repository.
Here is the link: [https://github.com/mvandenhi/sctree-supplementary-public/tree/main](url)

**Comment by sky-Yongjie-Xu** [comment]
Hi Moritz Vandenhirtz,
Thank you for your response, which successfully resolved my issue.
Additionally, during the reproduction process, I observed that the metrics' results are not very stable across different random seeds, with some results differing significantly from those reported in the original paper.
In your opinion, which hyperparameters are most likely to have a strong impact on the model's performance?
Regards,

Yongjie
________________________________
发件人: mvandenhi ***@***.***>
发送时间: 2024年9月24日 22:03
收件人: mvandenhi/sctree-public ***@***.***>
抄送: Yongjie Xu ***@***.***>; Author ***@***.***>
主题: Re: [mvandenhi/sctree-public] Is it possible to update the code for saving tree structures and for tree plotting? (Issue #1)


Hi Yongjie Xu,
Thank you for reaching out. We have added a Jupyter notebook to the main repository, which will visualize the learned tree. It requires some manual work depending on the dataset, however, the basic building blocks are the same. Please note that the trees are already automatically saved when running from the main repository.
Here is the link: https://github.com/mvandenhi/sctree-supplementary-public/tree/main<url>

―
